#!/usr/bin/env node
const selectEnvironment = require('./lib/selectEnvironment');
const gestalt = require('./lib/gestalt');

try {
    selectEnvironment.run({}, (result) => {
        if (result) {
            gestalt.setCurrentEnvironment(result);

            console.log();
            console.log(`${result.name} selected.`);
            console.log();
        } else {
            console.log("No selection.");
        }
    });

} catch (err) {
    console.log(err.message);
    console.log("Try running 'change-context'");
    console.log();
}
