#!/usr/bin/env node
const selectOrg = require('./lib/selectOrg');
const gestalt = require('./lib/gestalt');

try {
    selectOrg.run((result) => {
        if (result) {
            gestalt.setCurrentOrg(result);
            console.log();
            console.log(`${result.fqon} selected.`);
            console.log();
        } else {
            console.log("No selection.");
        }
    });
} catch (err) {
    console.log(err.message);
    console.log("Try running 'change-context'");
    console.log();
}

