#!/usr/bin/env node
const selectHierarchy = require('./lib/selectHierarchy');

try {
    selectHierarchy.chooseEnvironment(result => {
        // Nothing
    });
} catch (err) {
    console.log(err);
    console.log("Try running 'change-context'");
    console.log();
}
