#!/usr/bin/env node
const argv = require('yargs').argv
const gestalt = require('./lib/gestalt')
const displayResource = require('./lib/displayResourceUI');

const options = {
    message: "Workspaces",
    headers: ['Workspace', 'Name', 'Org', 'Owner'],
    fields: ['description', 'name', 'org.properties.fqon', 'owner.name'],
    sortField: 'description',
}

const resources = gestalt.fetchWorkspaces(gestalt.fetchOrgFqons());

// console.log(JSON.stringify(resources, null, 2))

displayResource.run(options, resources);
