#!/usr/bin/env node
const argv = require('yargs').argv
const gestalt = require('./lib/gestalt')
const displayResource = require('./lib/displayResourceUI');

const options = {
    message: "Orgs",
    headers: ['Org Name', 'FQON', 'Owner'],
    fields: ['description', 'properties.fqon', 'owner.name'],
    sortField: 'description',
}

const resources = gestalt.fetchOrgs();

// console.log(JSON.stringify(resources, null, 2))

displayResource.run(options, resources);
