#!/usr/bin/env node
const argv = require('yargs').argv
const gestalt = require('./lib/gestalt')
const displayResource = require('./lib/displayResourceUI');

const options = {
    message: "Workspaces",
    headers: ['Workspace', 'Name', 'Org', 'Owner'],
    fields: ['description', 'name', 'org.properties.fqon', 'owner.name'],
    sortField: 'description',
}

try {
    let resources = [];
    gestalt.fetchOrgFqons().map(fqon => {
        console.error(`Fetching from ${fqon}...`)
        const res = gestalt.fetchWorkspaces([fqon]);
        resources = resources.concat(res);
    });

    displayResource.run(options, resources);

} catch (err) {
    console.log(err.message);
    console.log("Try running 'switch-context'");
    console.log();
}
