#!/usr/bin/env node
const argv = require('yargs').argv
const gestalt = require('./lib/gestalt')
const displayResource = require('./lib/displayResourceUI');
const chalk = require('chalk')

let resources = [];

gestalt.fetchOrgFqons().map(fqon => {

    console.error(`Fetching from ${fqon}...`)
    const res = gestalt.fetchOrgContainers(fqon);

    res.map(item => {
        item.fqon = fqon
    })

    resources = resources.concat(res);

});

// console.log(resources)

const options = {
    headers: ['Container', 'FQON'],
    fields: ['name', 'fqon'],
    sortField: 'name',
}

try {
    displayResource.run(options, resources);
} catch (err) {
    console.log(err.message);
    console.log("Try running 'switch-context'");
    console.log();
}
