#!/usr/bin/env node
const argv = require('yargs').argv
const gestalt = require('./lib/gestalt')
const displayResource = require('./lib/displayResourceUI');

const options = {
    message: "Providers",
    headers: ['Provider', 'Description', 'Type', 'Org', 'Owner', /*'Created'*/],
    fields: ['name', 'description', 'resource_type', 'org.properties.fqon', 'owner.name', /*'created.timestamp'*/],
    sortField: 'name',
}

try {
    const fqon = gestalt.getState().org.fqon;
    
    const resources = gestalt.fetchOrgProviders([fqon]);

    resources.map(item => {
        item.resource_type = item.resource_type.replace(/Gestalt::Configuration::Provider::/, '')
    });
    
    // console.log(JSON.stringify(resources, null, 2))
    
    displayResource.run(options, resources);
} catch (err) {
    console.log(err.message);
    console.log("Try running 'switch-context'");
    console.log();
}
