#!/usr/bin/env node
const argv = require('yargs').argv
const selectProvider = require('./lib/selectProvider');

function showRaw(obj) {
    console.log()
    console.log(JSON.stringify(obj, null, 2));
    console.log()
}

// Main
try {

    // 1) Select Container

    selectProvider.run((provider) => {

        // 2) Show provider details

        showRaw(provider);
    });
} catch (err) {
    console.log(err.message);
    console.log("Try running 'switch'");
    console.log();
}
