#!/usr/bin/env node

const selectOrg = require('./lib/selectOrg');
const selectWorkspace = require('./lib/selectWorkspace');
const selectEnvironment = require('./lib/selectEnvironment');
const selectContainer = require('./lib/selectContainer');

selectOrg.run((result) => {

    console.log();
    console.log(`${result.org.fqon} selected.`);
    console.log();

    selectWorkspace.run((result) => {

        console.log();
        console.log(`${result.workspace.name} selected.`);
        console.log();

        selectEnvironment.run((result) => {

            console.log();
            console.log(`${result.environment.name} selected.`);
            console.log();
        });
    });
});
