#!/usr/bin/env node
const selectWorkspace = require('./lib/selectWorkspace');

try {
    selectWorkspace.run((result) => {
        console.log();    
        console.log(`${result.workspace.name} selected.`);
        console.log();
    });
    
} catch (err) {
    console.log(err.message);
    console.log("Try running 'select-context'");
    console.log();
}


