#!/usr/bin/env node
const selectContainer = require('./lib/selectContainer');
const gestalt = require('./lib/gestalt');

try {
    selectContainer.run({}, (result) => {
        if (result) {
            gestalt.setCurrentContainer(result);

            console.log();
            console.log(`${result.name} selected.`);
            console.log();
        } else {
            console.log("No selection.");
        }
    });
} catch (err) {
    console.log(err.message);
    console.log("Try running 'change-context'");
    console.log();
}