#!/usr/bin/env node
const selectWorkspace = require('./lib/selectWorkspace');
selectWorkspace.run((result) => {
    console.log();    
    console.log(`${result.workspace.name} selected.`);
    console.log();
});
