#!/usr/bin/env node
const selectEnvironment = require('./lib/selectEnvironment');

try {
    selectEnvironment.run((result) => {
        console.log();    
        console.log(`${result.environment.name} selected.`);
        console.log();
    });
    
} catch (err) {
    console.log(err.message);
    console.log("Try running 'select-context'");
    console.log();
}

