#!/usr/bin/env node
const selectEnvironment = require('./lib/selectEnvironment');
selectEnvironment.run((result) => {
    console.log();    
    console.log(`${result.environment.name} selected.`);
    console.log();
});
