#!/usr/bin/env node
const selectContainer = require('./lib/selectContainer');

try {
    selectContainer.run((result) => {
        console.log();
        console.log(`${result.container.name} selected.`);
        console.log();
    });
} catch (err) {
    console.log(err.message);
    console.log("Try running 'switch-context'");
    console.log();
}

