#!/usr/bin/env node
const argv = require('yargs').argv
const gestalt = require('./lib/gestalt')
const selectResource = require('./lib/selectResourceUI');

selectResource.mode = 'autocomplete';

function sortBy(arr, key) {
    return arr.sort((a, b) => {
        if (a[key] < b[key]) { return -1; }
        if (a[key] > b[key]) { return 1; }
        return 0;
    })
}

const options = {
    message: "Select Container",
    valueKey: 'value',
    fields: ['name', 'href'],
    returnValue: "container",
    fetchFunction: fetchFunction
}

selectResource.run(options, answers => {
    gestalt.persistState(answers);
});

function fetchFunction() {
    
    let resources = [];
    
    gestalt.fetchOrgFqons().map(fqon => {
    
        const res = gestalt.fetchOrgContainers(fqon);
    
        res.map(item => {
            item.fqon = fqon
            item.value = {
                id: item.id,
                name: item.name,
                fqon: item.fqon,
                href: item.href
            }
        })
    
        resources = resources.concat(res);
    });
    
    
    const options = {
        headers: ['Container', 'Link'],
        fields: ['name', 'href'],
        sortField: 'name',
    }
    
    // return resources;

    return sortBy(resources, 'name');
}
