#!/usr/bin/env node
const argv = require('yargs').argv
const gestalt = require('./lib/gestalt')

function showRaw(c) {
    console.log()
    console.log(JSON.stringify(c, null, 2));
    // console.log(c);
    console.log()
}

// Main

try {
    const container = gestalt.fetchContainer();
    
    showRaw(container);
} catch (err) {
    console.log(err.message);
    console.log("Try running 'select-container'");
    console.log();
}
