#!/usr/bin/env node
const argv = require('yargs').argv
const selectContainer = require('./lib/selectContainer');

function showRaw(c) {
    console.log()
    console.log(JSON.stringify(c, null, 2));
    console.log()
}

// Main
try {

    // 1) Select Container

    selectContainer.run((result) => {

        // 2) Show container details

        const container = result.container;

        showRaw(container);
    });
} catch (err) {
    console.log(err.message);
    console.log("Try running 'switch-context'");
    console.log();
}
