#!/usr/bin/env node
const argv = require('yargs').argv
const gestalt = require('./lib/gestalt')
const displayResource = require('./lib/displayResourceUI');

const options = {
    message: "Environments",
    headers: ['Environment', 'Name', 'Type', 'Org', 'Workspace', 'Owner'],
    fields: ['description', 'name', 'properties.environment_type', 'org.properties.fqon', 'properties.workspace.name', 'owner.name'],
    sortField: 'description',
}
const resources = gestalt.fetchOrgEnvironments();

console.log(JSON.stringify(resources, null, 2))

displayResource.run(options, resources);
