#!/usr/bin/env node
'use strict';

const argv = require('yargs').argv
const gestalt = require('./lib/gestalt')
const displayEntitlements = require('./lib/displayEntitlements');

try {
    const resources = gestalt.fetchWorkspaceEntitlements();
    
    displayEntitlements.run(resources);
    
} catch (err) {
    console.log(err.message);
    console.log("Try running 'change-context'");
    console.log();
}


