#!/usr/bin/env node
const argv = require('yargs').argv
const gestalt = require('./lib/gestalt')
const displayResource = require('./lib/displayResourceUI');

const options = {
    message: "Lambdas",
    headers: ['Lambda', 'Runtime', 'Public', 'FQON', 'Type', 'Owner'],
    fields: ['name', 'properties.runtime', 'properties.public', 'org.properties.fqon', 'properties.code_type', 'owner.name'],
    sortField: 'description',
}

const resources = gestalt.fetchLambdas();
// console.log(JSON.stringify(resources, null, 2))
resources.map(item => {
    //
})

// console.log(JSON.stringify(resources, null, 2))

displayResource.run(options, resources);
console.log();