#!/usr/bin/env node
const selectEnvironment = require('./lib/selectEnvironment');
const gestalt = require('./lib/gestalt');

try {
    selectEnvironment.run((result) => {
        gestalt.setCurrentEnvironment(result);                    

        console.log();    
        console.log(`${result.environment.name} selected.`);
        console.log();
    });
    
} catch (err) {
    console.log(err.message);
    console.log("Try running 'switch-context'");
    console.log();
}

